### ISSUE TITLE
Assignment 1-3 - Functions

### ISSUE THREAD

**Issue by ambethia** [Kessaku/assignments#3]
### Objectives

After completing this assignment, you should be able to:

* Understand JS syntax
* Demonstrate understanding of types, functions, argument-handling, loops, and conditional statements

### Details

Instructions

* `cd` into your project folder
* `mkdir <projectName>`, e.g. 'day-3-functions'
* `git init`
* `curl -O https://gist.githubusercontent.com/ambethia/3d472a76f5da83fb5d71/raw/functions.js`

* `node functions.js`

Modify `functions.js` to make the tests/assertions pass.

**Note**: The first two problems are the last two we didn't finish in class.

### Normal Mode

- [ ] All assertions in functions.js pass
- [ ] Turn in the homework as a repository on Github. Link to it in a comment on this issue.

#### Additional Resources

You might need to reference these to find what kind of helpful functions might already be on `Array` and `String` in JavaScript.

- [String Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String).
- [Array Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).

### Adventure Mode

- [ ] If you used any methods like `Array`'s `.reverse()` in your solutions, implemet the functions again without them.
- [ ] If you didn't use many built-in functions, look through the MDN documentation linked above and see if you can make use of any to refactor your code.

**Comment by Kessaku** [comment]
/**
 * Part 1
 *
 * Define a function reverse() that computes
 * the reversal of a string. For example,
 * reverse("skoob") should return the
 * string "books".
 */

function reverse(str){
    // YOUR CODE HERE
}
function reverse(str)
{
  var array = str.split("");
  array = array.reverse();
  return array.join("");
}
console.assert(reverse("books") === "skoob")
console.assert(reverse("we don't want no trouble") === "elbuort on tnaw t'nod ew")

/**
 * Part 2
 *
 * Write a function findLongestWord() that takes an
 * string returns the first, longest word in the array.
 *
 * i.e. findLongestWord("book dogs") should return "book"
 */

  function findLongestWord(sentence)
  {
      var array = sentence.split(" ");
      var longestWord = " ";

      for(i = 0; i < array.length; i++)
      {
        if (array[i].length > longestWord.length)
        {
          longestWord = array[i];
        }
      }
      return longestWord;
  }

console.assert(findLongestWord("book dogs") === "book")
console.assert(findLongestWord("don't mess with Florida") === "Florida")

/**
 * Part 3
 *
 * Write a function that calculates the sum of all the numbers in an array
 */

function sumOfArray(arr){
    var sum = 0;

      for (i = 0; i < arr.length; i++)
      {
        sum = sum + arr[i];
      }

    return sum;
}

console.assert(sumOfArray([1, 2]) === 3);
console.assert(sumOfArray([]) === 0);
console.assert(sumOfArray([1, 2, 3]) === 6);
console.assert(sumOfArray([10, 9, 8]) === 27);

/**
 * Part 4
 *
 * Write a function that takes two numbers as
 * arguments and computes the sum of those two numbers.
 */

function sum(a, b){
    return total = a + b;
}

console.assert(sum(8, 11) === 19);
console.assert(sum(4, 100) === 104);

/**
 * Part 5
 *
 * write a function that finds the Greatest Common Denominator of two numbers
 * - if no GCD exists, return 1
 */

function GCD(a, b)
{
  if (a % b === 0)
  {
    console.log(a,b)
    return b;
  }
  else
  {
    
  }

}

console.assert(GCD(5,1) === 1);
console.assert(GCD(15,3) === 3);
console.assert(GCD(15,5) === 5);
console.assert(GCD(50,20) === 10);

/**
 * Part 6
 *
 * write a function that prints out the Least Common Multiple of two numbers
 */

function LCM(a, b){
    // YOUR CODE HERE
}

console.assert(LCM(10,10) === 10)
console.assert(LCM(2,5) === 10)
console.assert(LCM(3,6) === 6)
console.assert(LCM(0,1) === 1)

**Comment by Kessaku** [comment]
https://github.com/Kessaku/day_three/blob/master/functions.js

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/3ZHCdW8zxpSdq/200w_d.gif)
